### ISSUE TITLE
Figure styling

### ISSUE THREAD

**Issue by krezelj** [krezelj/academia#213]
It's important that we agree upon a single style for all figures. Obviously some exceptions may occur but in general the styling should be consistent. Some things I suggest but as always I'm open to discussion
- Captions/Titles -- while we do have the capability to include titles in our figures directly I think it's better that we use captions in latex since it's more consistent with other documents and articles in general
- STD Region -- in all experiments where there were multiple runs we should somehow incorporate the information about variance into the figure. The STD region is the best but sometimes individual run traces are more informative (see Dense Bridge Building). Either way I don't think the figure should display the mean trajectory only
- Consistent naming -- this is a small detail but not to be overlooked, I've noticed in some of the figures that we use "difficulty X" in the axis label and "difficulty x" in the figure title. It's probably clear that those mean the same thing but since "X" and "x" can have different meanings (e.g. probability) I think we should stick to only one casing.

Should any of you have any more suggestions we can discuss them here. No change is to big and it's better to redo all the figures than to submit a thesis with known flaws so keep that in mind :)

**Comment by maciejors** [comment]
- `ignore_outliers=True` (default)
- `show_stop_time=True`
