### ISSUE TITLE
Section names, formal / informal language

### ISSUE THREAD

**Issue by krezelj** [krezelj/academia#214]
An inconsistency I've noticed is that we sometimes use "Cool Section Name" and sometimes we use "Cool section name". We should choose one and stick to it. I generally prefer the first one but It's of little importance to me which one we use.

Another thing I think we should not be doing is using apostrophes in section names. This is a nitpick but the last section "What We've learnt" should be either "What We Have Learnt" or "What we have learnt".

**Comment by maciejors** [comment]
Contractions are used only in informal writing so I believe we should avoid them in our thesis altogether, not only in section titles

**Comment by krezelj** [comment]
That's what I was thinking too but I wasn't sure.

**Comment by maciejors** [comment]
another thing are phrasal verbs which are also informal. I think we might have plenty of them so we should look through what we've got and substitute them with regular verbs
