### ISSUE TITLE
References

### ISSUE THREAD

**Issue by krezelj** [krezelj/academia#216]
This is an obvious but probably the single most important issue. When writing *any* text using external sources we should cite it and add it to the references. While we can just add the citations at the end of writing I think it will be much *much* easier if we do it while writing since it will be much more difficult to do it later. At the very least we should keep the references saved somewhere with a note in which section and paragraph they were used. For now we can store them locally for individual use but we can try to think of a better way to store them so that we all have access to them.

I've noticed that the section "Introduction/Reinforcement Learning" has already been written but there are no citations or references. I don't know whether they were simply not added yet or if the text does not require them but since we haven't explicitly talked about this yet I wanted to make sure.

Also another obvious reminder -- don't copy/paste entire articles from other sources ***especially*** without citation.

**Comment by maciejors** [comment]
TODO: add references to environments' documentation when describing third-party environments
