### ISSUE TITLE
Task/Curriculum configuration exports

### ISSUE THREAD

**Issue by maciejors** [krezelj/academia#240]
I'm wondering whether we should remove methods for exporting task/curricula configurations (`LearningTask.save()` & `Curriculum.save()`). The primary reason for that is that I don't see any practical use for this feature, plus let's not forget these methods require updating every time we add/remove task/curriculum parameters. Exporting configurations will also become significantly more difficult once we add all the fancy stuff like variables and callbacks.

Let me know what you think

**Comment by krezelj** [comment]
I agree. Since the advanced configuration files are a mean to bypass coding it's probably not going to be very useful to save them, especially since in-code configuration is always going to be more flexible and if one is already written others can use it directly without the need for config files.
